name = "frag"
compatibility_date = "2025-03-21"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vercel/output/static"

[build]
command = "npm run build"

[env.production]
# These are handled in your Cloudflare dashboard, but can be added here if needed.
# NEXT_PUBLIC_SUPABASE_URL = "..."
