-- This script creates a new table 'comment_upvotes' to track likes on comments.
-- It also sets up Row Level Security policies to ensure users can only manage their own upvotes.

-- 1. Create the table
CREATE TABLE public.comment_upvotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id UUID NOT NULL REFERENCES public.comments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- A user can only upvote a specific comment once
    UNIQUE (comment_id, user_id)
);

-- 2. Enable Row Level Security
ALTER TABLE public.comment_upvotes ENABLE ROW LEVEL SECURITY;

-- 3. Create policies
CREATE POLICY "Users can insert their own upvote"
ON public.comment_upvotes FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own upvote"
ON public.comment_upvotes FOR DELETE TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Enable read access for all users"
ON public.comment_upvotes FOR SELECT
USING (true);
